### ISSUE TITLE
Hangman comments

### ISSUE THREAD

**Issue by stu-slicer** [LorenzoTurco/Hangman#1]
- I really like your word selector, from a random word API - very good.
- The ability to display a definition is a great feature.
- I like you’ve used several different classes for handing the different bits of functionality.
- I like that the handling of the word selection and checking guesses against the word are all handled by the `WordLIst` class.
- You could do more validation in the `askForLetter` method of `Interaction` rather than a separate method, for example forced it to lowercase, ensure it was an alphabetic character or ‘1’, ensured they only entered a single character. Also the Scanner object could be an instance variable, so only created the once rather than every time you ask for a letter.
- In your `Main` class I would have made the three main classes, Result etc, instance variables - which are created on initialisation.
- You don’t display the letters already guessed, which is a shame as part of requirement.
- Also guessing the same letter loses a life, which may be deliberate,
- I had a bit of trouble getting it to run, the package org.json in the pom.xml didn’t match the actual package used - json-simple.

**Comment by LorenzoTurco** [comment]
- [x] You could do more validation in the askForLetter method of Interaction -Added
- [x] In your Main class I would have made the three main classes, Result etc, instance variables... -Added
- [x] You don’t display the letters already guessed... -Fixed
- [x] Also guessing the same letter loses a life, which may be deliberate... -Changed
